### ISSUE TITLE
[mainpage] 랜덤게임 이미지에 링크 연결하기

### ISSUE THREAD

**Issue by GiYeons** [Introduce-Games/IntroduceGame#1]
## 목적
메인 페이지의 랜덤게임 뽑기 article에서 뽑기 결과로 나온 게임 이미지 클릭 시 해당 페이지로 이동하는 기능이 필요합니다.

## 작업 상세 내용
- [x] 이미지에 링크가 연결되도록 코드 수정할 것

**Comment by 001004sua** [comment]
제가 기능 추가하도록 하겠습니다!
